force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Apartment_Name__c.field-meta.xml
<CustomField>
    <fullName>Apartment_Name__c</fullName>
    <label>Apartment Name</label>
    <referenceTo>Apartment__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>AppartmentUnits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Property__c/fields/Area_in_SqFt__c.field-meta.xml
<CustomField>
    <fullName>Area_in_SqFt__c</fullName>
    <label>Area in SqFt</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Studio_Apartment</fullName>
                <label>Studio Apartment</label>
            </value>
            <value>
                <fullName>Loft</fullName>
            </value>
            <value>
                <fullName>Micro_Apartment</fullName>
                <label>Micro Apartment</label>
            </value>
            <value>
                <fullName>Pent_House</fullName>
                <label>Pent House</label>
            </value>
            <value>
                <fullName>Standard Apartment</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>2Bed 2Bath</fullName>
            </value>
            <value>
                <fullName>3Bed 2Bath</fullName>
            </value>
            <value>
                <fullName>3Bed 2.5Bath</fullName>
            </value>
            <value>
                <fullName>3Bed 3Bath</fullName>
            </value>
            <value>
                <fullName>4Bed 3Bath</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/relatedPropertiesController.cls
public with sharing class relatedPropertiesController {
    @AuraEnabled
    public static List<Property__c> getRelatedProperties(String aptId){
        List<Property__c> propertyList = [SELECT Id, Name, Area_in_SqFt__c, Unit_Type__c FROM Property__c WHERE Apartment_Name__c = :aptId];
        return propertyList;
    }
    @AuraEnabled
    public static Integer getRelatedPropertyCount(String aptId) {
        AggregateResult[] count = [SELECT Count(Id) FROM Property__c WHERE Apartment_Name__c = :aptId];
        // system.debug(count[0].get('expr0'));
        Integer intCount = Integer.valueOf(count[0].get('expr0'));
        return intCount;
    }
}