force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Apartment_Name__c.field-meta.xml
<CustomField>
    <fullName>Apartment_Name__c</fullName>
    <label>Apartment Name</label>
    <referenceTo>Apartment__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>AppartmentUnits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Property__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SearchProperties_CC.cls
public with sharing class SearchProperties_CC {
    @AuraEnabled

    public String searchText {
        get {
            return searchText;
        }
        set {
            searchtext = value;
        }
    }

    public Boolean recordsFound {
        get {
            return ((properties != null) && (properties.size() != 0));
        }
        set;
    }

    public Boolean searched {get; set;}

    public ApexPages.StandardSetController setCon {get; set;}

    public SearchProperties_CC() {
        searched=false;
    }
    
    public List<Property__c> properties {
        get{
            if (setCon != null){
                return(List<Property__c>)setCon.getRecords();
            }
            else {return null;}
        }
        set;
    }

    public void Search() {
        if(String.isNotBlank(searchText) && searchText.length() > 1){
            searchText = (searchText.endsWith('*') ? searchText : (searchText+'*'));

            List<sObject> properties = [FIND :searchText
                                        IN ALL FIELDS
                                        RETURNING Property__c(Name, Apartment_Name__c, City__c, Street_Address__c)][0];

            setCon = new ApexPages.StandardSetController(properties);
            setCon.setPageNumber(1);
            setCon.setPageSize(10);

            searched=true;
        }
        else {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Search input must be 2 or more characters.'));
        }
    }
    @AuraEnabled
    public static List<Property__c> SearchProperties(String searchKey){
         string searchText= + searchKey + '*';
         List<Property__c> properties = [FIND :searchText
                                        IN ALL FIELDS
                                        RETURNING Property__c(Id, Name, Apartment_Name__r.Name, Street_Address__c, City__c)][0];
        return properties;
    }
    
    @AuraEnabled
    public static List<Property__c> findProperties(){
        List<Property__c> propertylist = [select Id, Name, Apartment_Name__r.Name, Street_Address__c, City__c from Property__c];
        return propertylist;
    }
    
     @AuraEnabled
    public static map<String,Object> getParentDetailsWithoutWrapper(){
        map<String,Object> mapData = new map<String,Object>();
        list<Property__c> listProp  = new list<Property__c>();
            for(Property__c objProp : [Select Id, Name, Apartment_Name__r.Name, Street_Address__c, City__c
                                      from Property__c limit 5]){
                      listProp.add(objProp);                                                 
                
            }
        mapData.put('ParentDetails',JSON.serialize(listProp));
        return mapData;
    }

}