force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Apartment__c/fields/Cost_of_Building__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_Building__c</fullName>
    <label>Cost of Building</label>
    <precision>12</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Apartment__c/fields/Total_No_Of_Units__c.field-meta.xml
<CustomField>
    <fullName>Total_No_Of_Units__c</fullName>
    <label>Total No Of Units</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apartment__c/fields/Total_SqFt_of_the_Building__c.field-meta.xml
<CustomField>
    <fullName>Total_SqFt_of_the_Building__c</fullName>
    <label>Total SqFt of the Building</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Apartment_Name__c.field-meta.xml
<CustomField>
    <fullName>Apartment_Name__c</fullName>
    <label>Apartment Name</label>
    <referenceTo>Apartment__c</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>AppartmentUnits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Property__c/fields/Area_in_SqFt__c.field-meta.xml
<CustomField>
    <fullName>Area_in_SqFt__c</fullName>
    <label>Area in SqFt</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Property_ID__c.field-meta.xml
<CustomField>
    <fullName>Property_ID__c</fullName>
    <externalId>true</externalId>
    <label>Property ID</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Studio_Apartment</fullName>
                <label>Studio Apartment</label>
            </value>
            <value>
                <fullName>Loft</fullName>
            </value>
            <value>
                <fullName>Micro_Apartment</fullName>
                <label>Micro Apartment</label>
            </value>
            <value>
                <fullName>Pent_House</fullName>
                <label>Pent House</label>
            </value>
            <value>
                <fullName>Standard Apartment</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>2Bed 2Bath</fullName>
            </value>
            <value>
                <fullName>3Bed 2Bath</fullName>
            </value>
            <value>
                <fullName>3Bed 2.5Bath</fullName>
            </value>
            <value>
                <fullName>3Bed 3Bath</fullName>
            </value>
            <value>
                <fullName>4Bed 3Bath</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/relatedPropertiesControllerTest.cls
@isTest
private class relatedPropertiesControllerTest {
    @isTest static void getRelatedPropertyTest() {
        List<Property__c> propertyList = new List<Property__c>();
        Apartment__c apt = new Apartment__c();
        apt.Name = 'A';
        apt.Total_No_Of_Units__c = 10;
        apt.Total_SqFt_of_the_Building__c = 20;
        apt.Cost_of_Building__c = 1;
        insert apt;
        for (Integer i = 0; i < 200; i++) {
            Property__c newProp = new Property__c();
            newProp.Name = 'A' + i;
            newProp.Property_ID__c = 'AA101';
            newProp.Area_in_SqFt__c = 1000 + i;
            newProp.Unit_Type__c = 'Standard Apartment';
            newProp.Apartment_Name__c = apt.Id;
            propertyList.add(newProp);
        }
        insert propertyList;

        Test.startTest();
        List<Property__c> assertList = relatedPropertiesController.getRelatedProperties(apt.Id);
        Test.stopTest();
        System.assertEquals(assertList.size(), 200);
    }
    @isTest static void getRelatedPropertyCount() {
        List<Property__c> propertyList = new List<Property__c>();
        Apartment__c apt = new Apartment__c();
        apt.Name = 'A';
        apt.Total_No_Of_Units__c = 10;
        apt.Total_SqFt_of_the_Building__c = 20;
        apt.Cost_of_Building__c = 1;
        insert apt;
        for (Integer i = 0; i < 200; i++) {
            Property__c newProp = new Property__c();
            newProp.Name = 'A' + i;
            newProp.Property_ID__c = 'AA101';
            newProp.Area_in_SqFt__c = 1000 + i;
            newProp.Unit_Type__c = 'Standard Apartment';
            newProp.Apartment_Name__c = apt.Id;
            propertyList.add(newProp);
        }
        insert propertyList;

        Test.startTest();
        Integer assertCount = relatedPropertiesController.getRelatedPropertyCount(apt.Id);
        Test.stopTest();
        System.assertEquals(assertCount, 200);
    }
}