force-app/main/default/objects/Apartment__c/Apartment__c.object-meta.xml
<CustomObject>
    <label>Apartment</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apartments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Apartment__c/fields/Cost_of_Building__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_Building__c</fullName>
    <label>Cost of Building</label>
    <precision>12</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Apartment__c/fields/Total_No_Of_Units__c.field-meta.xml
<CustomField>
    <fullName>Total_No_Of_Units__c</fullName>
    <label>Total No Of Units</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apartment__c/fields/Total_SqFt_of_the_Building__c.field-meta.xml
<CustomField>
    <fullName>Total_SqFt_of_the_Building__c</fullName>
    <label>Total SqFt of the Building</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/newApartmentController.cls
public with sharing class newApartmentController {
    @AuraEnabled
    public static Apartment__c saveApartment(Apartment__c apt) {
        upsert apt;
        return apt;
    }

    @AuraEnabled
    public static Apartment__c getApartment(Apartment__c apt, String Id) {
        return [SELECT Total_SqFt_of_the_Building__c, Cost_of_Building__c, Total_No_Of_Units__c, Name FROM Apartment__c WHERE Id = :Id];
    }
}